name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: [7.3, 7.4, 8.0]

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
      with:
        php_version:  ${{ matrix.php_version }}
    - uses: php-actions/phpunit@v3
      with:
        php_version:  ${{ matrix.php_version }}
        php_extensions: xdebug
        configuration: phpunit.xml.dist
        args: --coverage-text
