name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: [8.4, 8.5]

    steps:
    - uses: actions/checkout@v7
    - uses: php-actions/composer@v6
      with:
        php_version:  ${{ matrix.php_version }}
    - uses: php-actions/phpunit@v4
      with:
        php_version:  ${{ matrix.php_version }}
        configuration: phpunit.xml.dist
